import { createFileRoute } from "@tanstack/react-router";
import { useEffect, useState } from "react";

type Product = { id: string; title: string; description?: string; price_cents: number; image_url?: string; in_stock: boolean };
type Fulfillment = { uuid: string; order_number?: string; status: string; customer_name: string; delivery_address: string; driver_name?: string; proof_of_delivery_url?: string; created_at: string };
const api = "/api/v1/odofy/merchants";
const statuses: Record<string, string> = { PENDING_PICKUP: "bg-blue-100 text-blue-700", EN_ROUTE: "bg-amber-100 text-amber-700", DELIVERED: "bg-green-100 text-green-700", UNDELIVERABLE: "bg-red-100 text-red-700", RETURNED_TO_MERCHANT: "bg-gray-100 text-gray-700" };

function MerchantDashboardPage() {
  const [email, setEmail] = useState(""); const [products, setProducts] = useState<Product[]>([]); const [orders, setOrders] = useState<Fulfillment[]>([]); const [selected, setSelected] = useState<Fulfillment | null>(null); const [showForm, setShowForm] = useState(false); const [editing, setEditing] = useState<Product | null>(null); const [form, setForm] = useState({ title: "", description: "", price_cents: "", image_url: "" }); const [error, setError] = useState("");
  useEffect(() => { const e = typeof window !== "undefined" ? sessionStorage.getItem("merchant_email") || "" : ""; setEmail(e); if (!e && typeof window !== "undefined") window.location.href = "/merchant-login"; }, []);
  const headers = { "Content-Type": "application/json", "X-Merchant-Email": email };
  const load = async () => { if (!email) return; try { const [p, o] = await Promise.all([fetch(`${api}/products`, { headers }), fetch(`${api}/fulfillment`, { headers })]); if (!p.ok || !o.ok) throw new Error("Could not load dashboard"); setProducts(await p.json()); setOrders(await o.json()); } catch (e) { setError(e instanceof Error ? e.message : "Could not load dashboard"); } };
  useEffect(() => { load(); }, [email]);
  const toggleStock = async (p: Product) => { const r = await fetch(`${api}/products/${p.id}/toggle-stock`, { method: "PATCH", headers, body: JSON.stringify({ in_stock: !p.in_stock }) }); if (r.ok) setProducts(products.map(x => x.id === p.id ? { ...x, in_stock: !p.in_stock } : x)); };
  const save = async (ev: React.FormEvent) => { ev.preventDefault(); const body = { title: form.title, description: form.description || undefined, price_cents: Number(form.price_cents), image_url: form.image_url || undefined }; const r = await fetch(`${api}/products${editing ? `/${editing.id}` : ""}`, { method: editing ? "PATCH" : "POST", headers, body: JSON.stringify(body) }); if (!r.ok) return setError("Unable to save item"); const item = await r.json(); setProducts(editing ? products.map(p => p.id === item.id ? item : p) : [item, ...products]); setShowForm(false); setEditing(null); setForm({ title: "", description: "", price_cents: "", image_url: "" }); };
  const remove = async (id: string) => { if (!confirm("Delete this item?")) return; const r = await fetch(`${api}/products/${id}`, { method: "DELETE", headers }); if (r.ok) setProducts(products.filter(p => p.id !== id)); };
  const edit = (p: Product) => { setEditing(p); setForm({ title: p.title, description: p.description || "", price_cents: String(p.price_cents), image_url: p.image_url || "" }); setShowForm(true); };
  return <main className="min-h-screen bg-gray-50 p-4"><div className="max-w-7xl mx-auto p-6 bg-white rounded-2xl border border-gray-50 shadow-lg my-6"><h1 className="text-2xl font-black text-gray-800 mb-6">Merchant Operations Hub</h1>{error && <p className="mb-4 rounded-lg bg-red-50 p-3 text-sm text-red-700">{error}</p>}
    <section><div className="flex items-center justify-between mb-4"><h2 className="text-lg font-bold text-gray-800">Product Inventory</h2><button onClick={() => { setEditing(null); setShowForm(true); }} className="bg-[#5E0009] hover:bg-[#4a0007] text-white font-bold py-2.5 px-5 rounded-xl text-xs transition-all shadow-md">Add Item</button></div>{showForm && <form onSubmit={save} className="mb-5 grid gap-3 rounded-xl bg-gray-50 p-4 sm:grid-cols-4"><input required placeholder="Title" value={form.title} onChange={e => setForm({ ...form, title: e.target.value })} className="rounded-lg border p-2"/><input required type="number" min="0" placeholder="Price cents" value={form.price_cents} onChange={e => setForm({ ...form, price_cents: e.target.value })} className="rounded-lg border p-2"/><input placeholder="Description" value={form.description} onChange={e => setForm({ ...form, description: e.target.value })} className="rounded-lg border p-2"/><input placeholder="Image URL" value={form.image_url} onChange={e => setForm({ ...form, image_url: e.target.value })} className="rounded-lg border p-2"/><div className="sm:col-span-4"><button className="rounded-lg bg-[#5E0009] px-4 py-2 text-sm font-bold text-white">Save</button><button type="button" onClick={() => setShowForm(false)} className="ml-2 rounded-lg border px-4 py-2 text-sm">Cancel</button></div></form>}<div className="overflow-x-auto"><table className="w-full text-left text-sm"><thead><tr className="border-b text-xs uppercase text-gray-500"><th className="p-3">Image</th><th className="p-3">Title</th><th className="p-3">Price</th><th className="p-3">Stock Status</th><th className="p-3">Actions</th></tr></thead><tbody>{products.map(p => <tr key={p.id} className="border-b"><td className="p-3"><img src={p.image_url} className="h-[50px] w-[50px] rounded object-cover" alt="" onError={e => { e.currentTarget.style.display = "none"; }}/></td><td className="p-3 font-semibold">{p.title}</td><td className="p-3">${(p.price_cents / 100).toFixed(2)}</td><td className="p-3"><label className="inline-flex cursor-pointer items-center"><input type="checkbox" checked={p.in_stock} onChange={() => toggleStock(p)} className="h-5 w-5 accent-[#5E0009]"/><span className="ml-2 text-xs">{p.in_stock ? "In stock" : "Out of stock"}</span></label></td><td className="p-3"><button onClick={() => edit(p)} className="mr-3 text-xs font-bold text-[#5E0009]">Edit</button><button onClick={() => remove(p.id)} className="text-xs font-bold text-red-600">Delete</button></td></tr>)}</tbody></table></div></section>
    <section className="mt-10"><h2 className="mb-4 text-lg font-bold text-gray-800">Active Order Fulfillment</h2><div className="overflow-x-auto"><table className="w-full text-left text-sm"><thead><tr className="border-b text-xs uppercase text-gray-500"><th className="p-3">Order ID</th><th className="p-3">Customer</th><th className="p-3">Status</th><th className="p-3">Driver</th><th className="p-3">Actions</th></tr></thead><tbody>{orders.map(o => <tr key={o.uuid} onClick={() => setSelected(o)} className="cursor-pointer border-b hover:bg-gray-50"><td className="p-3 font-mono">{o.order_number || o.uuid.slice(0, 8)}</td><td className="p-3">{o.customer_name}</td><td className="p-3"><span className={`rounded-full px-2 py-1 text-xs font-bold ${statuses[o.status] || statuses.RETURNED_TO_MERCHANT}`}>{o.status}</span></td><td className="p-3">{o.driver_name || "Unassigned"}</td><td className="p-3 text-xs text-[#5E0009]">View details</td></tr>)}</tbody></table></div></section>
  </div>{selected && <div className="fixed inset-0 z-50 flex items-center justify-center bg-black/40 p-4" onClick={() => setSelected(null)}><div onClick={e => e.stopPropagation()} className="w-full max-w-lg rounded-2xl bg-white p-6 shadow-xl"><h2 className="text-xl font-bold">Order {selected.order_number || selected.uuid.slice(0, 8)}</h2><dl className="mt-4 space-y-2 text-sm"><p><b>Customer:</b> {selected.customer_name}</p><p><b>Status:</b> {selected.status}</p><p><b>Driver:</b> {selected.driver_name || "Unassigned"}</p><p><b>Address:</b> {selected.delivery_address}</p></dl>{selected.proof_of_delivery_url ? <img src={selected.proof_of_delivery_url} className="mt-4 max-h-64 w-full rounded object-contain" alt="Proof of delivery"/> : <p className="mt-4 rounded bg-gray-50 p-5 text-center text-sm text-gray-500">No proof of delivery yet</p>}<button onClick={() => setSelected(null)} className="mt-5 rounded-lg bg-[#5E0009] px-4 py-2 text-sm font-bold text-white">Close</button></div></div>}</main>;
}
export const Route = createFileRoute("/merchant/dashboard")({ component: MerchantDashboardPage });
