/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TripsRouteImport } from './routes/trips'
import { Route as TrackRouteImport } from './routes/track'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as ProfileMenuRouteImport } from './routes/profile-menu'
import { Route as OrderRouteImport } from './routes/order'
import { Route as NotificationsRouteImport } from './routes/notifications'
import { Route as MerchantSignupRouteImport } from './routes/merchant-signup'
import { Route as MerchantLoginRouteImport } from './routes/merchant-login'
import { Route as MerchantRouteImport } from './routes/merchant'
import { Route as EarningsHistoryRouteImport } from './routes/earnings-history'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TOrderIdRouteImport } from './routes/t.$orderId'
import { Route as AdminTaxesRouteImport } from './routes/admin/taxes'

const TripsRoute = TripsRouteImport.update({
  id: '/trips',
  path: '/trips',
  getParentRoute: () => rootRouteImport,
} as any)
const TrackRoute = TrackRouteImport.update({
  id: '/track',
  path: '/track',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileMenuRoute = ProfileMenuRouteImport.update({
  id: '/profile-menu',
  path: '/profile-menu',
  getParentRoute: () => rootRouteImport,
} as any)
const OrderRoute = OrderRouteImport.update({
  id: '/order',
  path: '/order',
  getParentRoute: () => rootRouteImport,
} as any)
const NotificationsRoute = NotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const MerchantSignupRoute = MerchantSignupRouteImport.update({
  id: '/merchant-signup',
  path: '/merchant-signup',
  getParentRoute: () => rootRouteImport,
} as any)
const MerchantLoginRoute = MerchantLoginRouteImport.update({
  id: '/merchant-login',
  path: '/merchant-login',
  getParentRoute: () => rootRouteImport,
} as any)
const MerchantRoute = MerchantRouteImport.update({
  id: '/merchant',
  path: '/merchant',
  getParentRoute: () => rootRouteImport,
} as any)
const EarningsHistoryRoute = EarningsHistoryRouteImport.update({
  id: '/earnings-history',
  path: '/earnings-history',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TOrderIdRoute = TOrderIdRouteImport.update({
  id: '/t/$orderId',
  path: '/t/$orderId',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminTaxesRoute = AdminTaxesRouteImport.update({
  id: '/taxes',
  path: '/taxes',
  getParentRoute: () => AdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/dashboard': typeof DashboardRoute
  '/earnings-history': typeof EarningsHistoryRoute
  '/merchant': typeof MerchantRoute
  '/merchant-login': typeof MerchantLoginRoute
  '/merchant-signup': typeof MerchantSignupRoute
  '/notifications': typeof NotificationsRoute
  '/order': typeof OrderRoute
  '/profile-menu': typeof ProfileMenuRoute
  '/register': typeof RegisterRoute
  '/track': typeof TrackRoute
  '/trips': typeof TripsRoute
  '/admin/taxes': typeof AdminTaxesRoute
  '/t/$orderId': typeof TOrderIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/dashboard': typeof DashboardRoute
  '/earnings-history': typeof EarningsHistoryRoute
  '/merchant': typeof MerchantRoute
  '/merchant-login': typeof MerchantLoginRoute
  '/merchant-signup': typeof MerchantSignupRoute
  '/notifications': typeof NotificationsRoute
  '/order': typeof OrderRoute
  '/profile-menu': typeof ProfileMenuRoute
  '/register': typeof RegisterRoute
  '/track': typeof TrackRoute
  '/trips': typeof TripsRoute
  '/admin/taxes': typeof AdminTaxesRoute
  '/t/$orderId': typeof TOrderIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/dashboard': typeof DashboardRoute
  '/earnings-history': typeof EarningsHistoryRoute
  '/merchant': typeof MerchantRoute
  '/merchant-login': typeof MerchantLoginRoute
  '/merchant-signup': typeof MerchantSignupRoute
  '/notifications': typeof NotificationsRoute
  '/order': typeof OrderRoute
  '/profile-menu': typeof ProfileMenuRoute
  '/register': typeof RegisterRoute
  '/track': typeof TrackRoute
  '/trips': typeof TripsRoute
  '/admin/taxes': typeof AdminTaxesRoute
  '/t/$orderId': typeof TOrderIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/dashboard'
    | '/earnings-history'
    | '/merchant'
    | '/merchant-login'
    | '/merchant-signup'
    | '/notifications'
    | '/order'
    | '/profile-menu'
    | '/register'
    | '/track'
    | '/trips'
    | '/admin/taxes'
    | '/t/$orderId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/dashboard'
    | '/earnings-history'
    | '/merchant'
    | '/merchant-login'
    | '/merchant-signup'
    | '/notifications'
    | '/order'
    | '/profile-menu'
    | '/register'
    | '/track'
    | '/trips'
    | '/admin/taxes'
    | '/t/$orderId'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/dashboard'
    | '/earnings-history'
    | '/merchant'
    | '/merchant-login'
    | '/merchant-signup'
    | '/notifications'
    | '/order'
    | '/profile-menu'
    | '/register'
    | '/track'
    | '/trips'
    | '/admin/taxes'
    | '/t/$orderId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  DashboardRoute: typeof DashboardRoute
  EarningsHistoryRoute: typeof EarningsHistoryRoute
  MerchantRoute: typeof MerchantRoute
  MerchantLoginRoute: typeof MerchantLoginRoute
  MerchantSignupRoute: typeof MerchantSignupRoute
  NotificationsRoute: typeof NotificationsRoute
  OrderRoute: typeof OrderRoute
  ProfileMenuRoute: typeof ProfileMenuRoute
  RegisterRoute: typeof RegisterRoute
  TrackRoute: typeof TrackRoute
  TripsRoute: typeof TripsRoute
  TOrderIdRoute: typeof TOrderIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/trips': {
      id: '/trips'
      path: '/trips'
      fullPath: '/trips'
      preLoaderRoute: typeof TripsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/track': {
      id: '/track'
      path: '/track'
      fullPath: '/track'
      preLoaderRoute: typeof TrackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile-menu': {
      id: '/profile-menu'
      path: '/profile-menu'
      fullPath: '/profile-menu'
      preLoaderRoute: typeof ProfileMenuRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/order': {
      id: '/order'
      path: '/order'
      fullPath: '/order'
      preLoaderRoute: typeof OrderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notifications': {
      id: '/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof NotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/merchant-signup': {
      id: '/merchant-signup'
      path: '/merchant-signup'
      fullPath: '/merchant-signup'
      preLoaderRoute: typeof MerchantSignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/merchant-login': {
      id: '/merchant-login'
      path: '/merchant-login'
      fullPath: '/merchant-login'
      preLoaderRoute: typeof MerchantLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/merchant': {
      id: '/merchant'
      path: '/merchant'
      fullPath: '/merchant'
      preLoaderRoute: typeof MerchantRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/earnings-history': {
      id: '/earnings-history'
      path: '/earnings-history'
      fullPath: '/earnings-history'
      preLoaderRoute: typeof EarningsHistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/t/$orderId': {
      id: '/t/$orderId'
      path: '/t/$orderId'
      fullPath: '/t/$orderId'
      preLoaderRoute: typeof TOrderIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/taxes': {
      id: '/admin/taxes'
      path: '/taxes'
      fullPath: '/admin/taxes'
      preLoaderRoute: typeof AdminTaxesRouteImport
      parentRoute: typeof AdminRoute
    }
  }
}

interface AdminRouteChildren {
  AdminTaxesRoute: typeof AdminTaxesRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminTaxesRoute: AdminTaxesRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  DashboardRoute: DashboardRoute,
  EarningsHistoryRoute: EarningsHistoryRoute,
  MerchantRoute: MerchantRoute,
  MerchantLoginRoute: MerchantLoginRoute,
  MerchantSignupRoute: MerchantSignupRoute,
  NotificationsRoute: NotificationsRoute,
  OrderRoute: OrderRoute,
  ProfileMenuRoute: ProfileMenuRoute,
  RegisterRoute: RegisterRoute,
  TrackRoute: TrackRoute,
  TripsRoute: TripsRoute,
  TOrderIdRoute: TOrderIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
