/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as CalculatorRouteImport } from './routes/calculator'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as EarningsHistoryRouteImport } from './routes/earnings-history'
import { Route as MerchantRouteImport } from './routes/merchant'
import { Route as MerchantLoginRouteImport } from './routes/merchant-login'
import { Route as MerchantSignupRouteImport } from './routes/merchant-signup'
import { Route as NotificationsRouteImport } from './routes/notifications'
import { Route as OrderRouteImport } from './routes/order'
import { Route as OverviewRouteImport } from './routes/overview'
import { Route as ProfileMenuRouteImport } from './routes/profile-menu'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as StoreRouteImport } from './routes/store'
import { Route as TrackRouteImport } from './routes/track'
import { Route as TripsRouteImport } from './routes/trips'
import { Route as AdminDriversRouteImport } from './routes/admin/drivers'
import { Route as AdminTaxesRouteImport } from './routes/admin/taxes'
import { Route as CompareFlatFeeVsCommissionRouteImport } from './routes/compare.flat-fee-vs-commission'
import { Route as CustomerDashboardRouteImport } from './routes/customer/dashboard'
import { Route as MerchantDashboardRouteImport } from './routes/merchant/dashboard'
import { Route as MerchantMarketingRouteImport } from './routes/merchant/marketing'
import { Route as StoreIndexRouteImport } from './routes/store/index'
import { Route as StoreMerchant_slugRouteImport } from './routes/store/$merchant_slug'
import { Route as StoreStMichaelsRouteImport } from './routes/store/st-michaels'
import { Route as TOrderIdRouteImport } from './routes/t.$orderId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const CalculatorRoute = CalculatorRouteImport.update({
  id: '/calculator',
  path: '/calculator',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const EarningsHistoryRoute = EarningsHistoryRouteImport.update({
  id: '/earnings-history',
  path: '/earnings-history',
  getParentRoute: () => rootRouteImport,
} as any)
const MerchantRoute = MerchantRouteImport.update({
  id: '/merchant',
  path: '/merchant',
  getParentRoute: () => rootRouteImport,
} as any)
const MerchantLoginRoute = MerchantLoginRouteImport.update({
  id: '/merchant-login',
  path: '/merchant-login',
  getParentRoute: () => rootRouteImport,
} as any)
const MerchantSignupRoute = MerchantSignupRouteImport.update({
  id: '/merchant-signup',
  path: '/merchant-signup',
  getParentRoute: () => rootRouteImport,
} as any)
const NotificationsRoute = NotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const OrderRoute = OrderRouteImport.update({
  id: '/order',
  path: '/order',
  getParentRoute: () => rootRouteImport,
} as any)
const OverviewRoute = OverviewRouteImport.update({
  id: '/overview',
  path: '/overview',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileMenuRoute = ProfileMenuRouteImport.update({
  id: '/profile-menu',
  path: '/profile-menu',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const StoreRoute = StoreRouteImport.update({
  id: '/store',
  path: '/store',
  getParentRoute: () => rootRouteImport,
} as any)
const TrackRoute = TrackRouteImport.update({
  id: '/track',
  path: '/track',
  getParentRoute: () => rootRouteImport,
} as any)
const TripsRoute = TripsRouteImport.update({
  id: '/trips',
  path: '/trips',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminDriversRoute = AdminDriversRouteImport.update({
  id: '/drivers',
  path: '/drivers',
  getParentRoute: () => AdminRoute,
} as any)
const AdminTaxesRoute = AdminTaxesRouteImport.update({
  id: '/taxes',
  path: '/taxes',
  getParentRoute: () => AdminRoute,
} as any)
const CompareFlatFeeVsCommissionRoute =
  CompareFlatFeeVsCommissionRouteImport.update({
    id: '/compare/flat-fee-vs-commission',
    path: '/compare/flat-fee-vs-commission',
    getParentRoute: () => rootRouteImport,
  } as any)
const CustomerDashboardRoute = CustomerDashboardRouteImport.update({
  id: '/customer/dashboard',
  path: '/customer/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const MerchantDashboardRoute = MerchantDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => MerchantRoute,
} as any)
const MerchantMarketingRoute = MerchantMarketingRouteImport.update({
  id: '/marketing',
  path: '/marketing',
  getParentRoute: () => MerchantRoute,
} as any)
const StoreIndexRoute = StoreIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => StoreRoute,
} as any)
const StoreMerchant_slugRoute = StoreMerchant_slugRouteImport.update({
  id: '/$merchant_slug',
  path: '/$merchant_slug',
  getParentRoute: () => StoreRoute,
} as any)
const StoreStMichaelsRoute = StoreStMichaelsRouteImport.update({
  id: '/st-michaels',
  path: '/st-michaels',
  getParentRoute: () => StoreRoute,
} as any)
const TOrderIdRoute = TOrderIdRouteImport.update({
  id: '/t/$orderId',
  path: '/t/$orderId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/calculator': typeof CalculatorRoute
  '/dashboard': typeof DashboardRoute
  '/earnings-history': typeof EarningsHistoryRoute
  '/merchant': typeof MerchantRouteWithChildren
  '/merchant-login': typeof MerchantLoginRoute
  '/merchant-signup': typeof MerchantSignupRoute
  '/notifications': typeof NotificationsRoute
  '/order': typeof OrderRoute
  '/overview': typeof OverviewRoute
  '/profile-menu': typeof ProfileMenuRoute
  '/register': typeof RegisterRoute
  '/store': typeof StoreRouteWithChildren
  '/track': typeof TrackRoute
  '/trips': typeof TripsRoute
  '/admin/drivers': typeof AdminDriversRoute
  '/admin/taxes': typeof AdminTaxesRoute
  '/compare/flat-fee-vs-commission': typeof CompareFlatFeeVsCommissionRoute
  '/customer/dashboard': typeof CustomerDashboardRoute
  '/merchant/dashboard': typeof MerchantDashboardRoute
  '/merchant/marketing': typeof MerchantMarketingRoute
  '/store/$merchant_slug': typeof StoreMerchant_slugRoute
  '/store/st-michaels': typeof StoreStMichaelsRoute
  '/t/$orderId': typeof TOrderIdRoute
  '/store/': typeof StoreIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/calculator': typeof CalculatorRoute
  '/dashboard': typeof DashboardRoute
  '/earnings-history': typeof EarningsHistoryRoute
  '/merchant': typeof MerchantRouteWithChildren
  '/merchant-login': typeof MerchantLoginRoute
  '/merchant-signup': typeof MerchantSignupRoute
  '/notifications': typeof NotificationsRoute
  '/order': typeof OrderRoute
  '/overview': typeof OverviewRoute
  '/profile-menu': typeof ProfileMenuRoute
  '/register': typeof RegisterRoute
  '/track': typeof TrackRoute
  '/trips': typeof TripsRoute
  '/admin/drivers': typeof AdminDriversRoute
  '/admin/taxes': typeof AdminTaxesRoute
  '/compare/flat-fee-vs-commission': typeof CompareFlatFeeVsCommissionRoute
  '/customer/dashboard': typeof CustomerDashboardRoute
  '/merchant/dashboard': typeof MerchantDashboardRoute
  '/merchant/marketing': typeof MerchantMarketingRoute
  '/store/$merchant_slug': typeof StoreMerchant_slugRoute
  '/store/st-michaels': typeof StoreStMichaelsRoute
  '/t/$orderId': typeof TOrderIdRoute
  '/store': typeof StoreIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/calculator': typeof CalculatorRoute
  '/dashboard': typeof DashboardRoute
  '/earnings-history': typeof EarningsHistoryRoute
  '/merchant': typeof MerchantRouteWithChildren
  '/merchant-login': typeof MerchantLoginRoute
  '/merchant-signup': typeof MerchantSignupRoute
  '/notifications': typeof NotificationsRoute
  '/order': typeof OrderRoute
  '/overview': typeof OverviewRoute
  '/profile-menu': typeof ProfileMenuRoute
  '/register': typeof RegisterRoute
  '/store': typeof StoreRouteWithChildren
  '/track': typeof TrackRoute
  '/trips': typeof TripsRoute
  '/admin/drivers': typeof AdminDriversRoute
  '/admin/taxes': typeof AdminTaxesRoute
  '/compare/flat-fee-vs-commission': typeof CompareFlatFeeVsCommissionRoute
  '/customer/dashboard': typeof CustomerDashboardRoute
  '/merchant/dashboard': typeof MerchantDashboardRoute
  '/merchant/marketing': typeof MerchantMarketingRoute
  '/store/$merchant_slug': typeof StoreMerchant_slugRoute
  '/store/st-michaels': typeof StoreStMichaelsRoute
  '/t/$orderId': typeof TOrderIdRoute
  '/store/': typeof StoreIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/calculator'
    | '/dashboard'
    | '/earnings-history'
    | '/merchant'
    | '/merchant-login'
    | '/merchant-signup'
    | '/notifications'
    | '/order'
    | '/overview'
    | '/profile-menu'
    | '/register'
    | '/store'
    | '/track'
    | '/trips'
    | '/admin/drivers'
    | '/admin/taxes'
    | '/compare/flat-fee-vs-commission'
    | '/customer/dashboard'
    | '/merchant/dashboard'
    | '/merchant/marketing'
    | '/store/$merchant_slug'
    | '/store/st-michaels'
    | '/t/$orderId'
    | '/store/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/calculator'
    | '/dashboard'
    | '/earnings-history'
    | '/merchant'
    | '/merchant-login'
    | '/merchant-signup'
    | '/notifications'
    | '/order'
    | '/overview'
    | '/profile-menu'
    | '/register'
    | '/track'
    | '/trips'
    | '/admin/drivers'
    | '/admin/taxes'
    | '/compare/flat-fee-vs-commission'
    | '/customer/dashboard'
    | '/merchant/dashboard'
    | '/merchant/marketing'
    | '/store/$merchant_slug'
    | '/store/st-michaels'
    | '/t/$orderId'
    | '/store'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/calculator'
    | '/dashboard'
    | '/earnings-history'
    | '/merchant'
    | '/merchant-login'
    | '/merchant-signup'
    | '/notifications'
    | '/order'
    | '/overview'
    | '/profile-menu'
    | '/register'
    | '/store'
    | '/track'
    | '/trips'
    | '/admin/drivers'
    | '/admin/taxes'
    | '/compare/flat-fee-vs-commission'
    | '/customer/dashboard'
    | '/merchant/dashboard'
    | '/merchant/marketing'
    | '/store/$merchant_slug'
    | '/store/st-michaels'
    | '/t/$orderId'
    | '/store/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  CalculatorRoute: typeof CalculatorRoute
  DashboardRoute: typeof DashboardRoute
  EarningsHistoryRoute: typeof EarningsHistoryRoute
  MerchantRoute: typeof MerchantRouteWithChildren
  MerchantLoginRoute: typeof MerchantLoginRoute
  MerchantSignupRoute: typeof MerchantSignupRoute
  NotificationsRoute: typeof NotificationsRoute
  OrderRoute: typeof OrderRoute
  OverviewRoute: typeof OverviewRoute
  ProfileMenuRoute: typeof ProfileMenuRoute
  RegisterRoute: typeof RegisterRoute
  StoreRoute: typeof StoreRouteWithChildren
  TrackRoute: typeof TrackRoute
  TripsRoute: typeof TripsRoute
  CompareFlatFeeVsCommissionRoute: typeof CompareFlatFeeVsCommissionRoute
  CustomerDashboardRoute: typeof CustomerDashboardRoute
  TOrderIdRoute: typeof TOrderIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calculator': {
      id: '/calculator'
      path: '/calculator'
      fullPath: '/calculator'
      preLoaderRoute: typeof CalculatorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/earnings-history': {
      id: '/earnings-history'
      path: '/earnings-history'
      fullPath: '/earnings-history'
      preLoaderRoute: typeof EarningsHistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/merchant': {
      id: '/merchant'
      path: '/merchant'
      fullPath: '/merchant'
      preLoaderRoute: typeof MerchantRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/merchant-login': {
      id: '/merchant-login'
      path: '/merchant-login'
      fullPath: '/merchant-login'
      preLoaderRoute: typeof MerchantLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/merchant-signup': {
      id: '/merchant-signup'
      path: '/merchant-signup'
      fullPath: '/merchant-signup'
      preLoaderRoute: typeof MerchantSignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notifications': {
      id: '/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof NotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/order': {
      id: '/order'
      path: '/order'
      fullPath: '/order'
      preLoaderRoute: typeof OrderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/overview': {
      id: '/overview'
      path: '/overview'
      fullPath: '/overview'
      preLoaderRoute: typeof OverviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile-menu': {
      id: '/profile-menu'
      path: '/profile-menu'
      fullPath: '/profile-menu'
      preLoaderRoute: typeof ProfileMenuRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/store': {
      id: '/store'
      path: '/store'
      fullPath: '/store'
      preLoaderRoute: typeof StoreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/track': {
      id: '/track'
      path: '/track'
      fullPath: '/track'
      preLoaderRoute: typeof TrackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trips': {
      id: '/trips'
      path: '/trips'
      fullPath: '/trips'
      preLoaderRoute: typeof TripsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/drivers': {
      id: '/admin/drivers'
      path: '/drivers'
      fullPath: '/admin/drivers'
      preLoaderRoute: typeof AdminDriversRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/taxes': {
      id: '/admin/taxes'
      path: '/taxes'
      fullPath: '/admin/taxes'
      preLoaderRoute: typeof AdminTaxesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/compare/flat-fee-vs-commission': {
      id: '/compare/flat-fee-vs-commission'
      path: '/compare/flat-fee-vs-commission'
      fullPath: '/compare/flat-fee-vs-commission'
      preLoaderRoute: typeof CompareFlatFeeVsCommissionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/customer/dashboard': {
      id: '/customer/dashboard'
      path: '/customer/dashboard'
      fullPath: '/customer/dashboard'
      preLoaderRoute: typeof CustomerDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/merchant/dashboard': {
      id: '/merchant/dashboard'
      path: '/dashboard'
      fullPath: '/merchant/dashboard'
      preLoaderRoute: typeof MerchantDashboardRouteImport
      parentRoute: typeof MerchantRoute
    }
    '/merchant/marketing': {
      id: '/merchant/marketing'
      path: '/marketing'
      fullPath: '/merchant/marketing'
      preLoaderRoute: typeof MerchantMarketingRouteImport
      parentRoute: typeof MerchantRoute
    }
    '/store/': {
      id: '/store/'
      path: '/'
      fullPath: '/store/'
      preLoaderRoute: typeof StoreIndexRouteImport
      parentRoute: typeof StoreRoute
    }
    '/store/$merchant_slug': {
      id: '/store/$merchant_slug'
      path: '/$merchant_slug'
      fullPath: '/store/$merchant_slug'
      preLoaderRoute: typeof StoreMerchant_slugRouteImport
      parentRoute: typeof StoreRoute
    }
    '/store/st-michaels': {
      id: '/store/st-michaels'
      path: '/st-michaels'
      fullPath: '/store/st-michaels'
      preLoaderRoute: typeof StoreStMichaelsRouteImport
      parentRoute: typeof StoreRoute
    }
    '/t/$orderId': {
      id: '/t/$orderId'
      path: '/t/$orderId'
      fullPath: '/t/$orderId'
      preLoaderRoute: typeof TOrderIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AdminRouteChildren {
  AdminDriversRoute: typeof AdminDriversRoute
  AdminTaxesRoute: typeof AdminTaxesRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminDriversRoute: AdminDriversRoute,
  AdminTaxesRoute: AdminTaxesRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface MerchantRouteChildren {
  MerchantDashboardRoute: typeof MerchantDashboardRoute
  MerchantMarketingRoute: typeof MerchantMarketingRoute
}

const MerchantRouteChildren: MerchantRouteChildren = {
  MerchantDashboardRoute: MerchantDashboardRoute,
  MerchantMarketingRoute: MerchantMarketingRoute,
}

const MerchantRouteWithChildren = MerchantRoute._addFileChildren(
  MerchantRouteChildren,
)

interface StoreRouteChildren {
  StoreMerchant_slugRoute: typeof StoreMerchant_slugRoute
  StoreStMichaelsRoute: typeof StoreStMichaelsRoute
  StoreIndexRoute: typeof StoreIndexRoute
}

const StoreRouteChildren: StoreRouteChildren = {
  StoreMerchant_slugRoute: StoreMerchant_slugRoute,
  StoreStMichaelsRoute: StoreStMichaelsRoute,
  StoreIndexRoute: StoreIndexRoute,
}

const StoreRouteWithChildren = StoreRoute._addFileChildren(StoreRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  CalculatorRoute: CalculatorRoute,
  DashboardRoute: DashboardRoute,
  EarningsHistoryRoute: EarningsHistoryRoute,
  MerchantRoute: MerchantRouteWithChildren,
  MerchantLoginRoute: MerchantLoginRoute,
  MerchantSignupRoute: MerchantSignupRoute,
  NotificationsRoute: NotificationsRoute,
  OrderRoute: OrderRoute,
  OverviewRoute: OverviewRoute,
  ProfileMenuRoute: ProfileMenuRoute,
  RegisterRoute: RegisterRoute,
  StoreRoute: StoreRouteWithChildren,
  TrackRoute: TrackRoute,
  TripsRoute: TripsRoute,
  CompareFlatFeeVsCommissionRoute: CompareFlatFeeVsCommissionRoute,
  CustomerDashboardRoute: CustomerDashboardRoute,
  TOrderIdRoute: TOrderIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
